name: coverage

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v4.1.6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
        pip install tox
    - name: Run Coverage
      run: |
        tox -r -e cov
    - name: Upload coverage
      uses: actions/upload-artifact@v4.3.3
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage.xml
        overwrite: true
  upload-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    needs:
      - coverage
    timeout-minutes: 10
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.6
      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          name: python-adc-eval
