name: coverage

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  coverage:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 1
      matrix:
        platform:
          - ubuntu-latest
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
        pip install tox
        pip install codecov
    - name: Test
      run: |
        tox -r -e cov
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./coverage.xml
        flags: unittests # optional
        name: python-adc-eval
        token: ${{ secrets.CODECOV_TOKEN }} # required
        verbose: true # optional (default = false)
